I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 272, in script
    $ personal_wealth_increased += 2
  File "game/script.rpy", line 272, in <module>
    $ personal_wealth_increased += 2
NameError: name 'personal_wealth_increased' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 272, in script
    $ personal_wealth_increased += 2
  File "C:\Users\cainj\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\cainj\Downloads\renpy-8.3.3-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 272, in <module>
    $ personal_wealth_increased += 2
NameError: name 'personal_wealth_increased' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.3.24111502
Cheiftain 1.0
Sun Mar 16 12:33:19 2025
